### ISSUE TITLE
Test WebUI core

### ISSUE THREAD

**Issue by nimishbongale** [rucio/webui#100]
### Description

With the addition of a lot of new code, there seems to be a lack in UTs. 

### Motivation

Get the coverage up, make code less bug prone

### Change

Create a corresponding `.test.tsx` file, or a `.test.ts` file and write tests (configured already)

**Comment by maany** [comment]
The goal is to have coverage in 1.31.0 > 60%

**Comment by maany** [comment]
Completed via #117
