### ISSUE TITLE
WebUI 2.0: Port views to new UI (High Priority)

### ISSUE THREAD

**Issue by maany** [rucio/webui#20]
Motivation
----------
- [ ] Rule View
- [ ] DID View
- [ ] List My Rules
- [ ] Request New Rules

**Comment by nimishbongale** [comment]
Let's use this issue to track our progress on the 4 pages, what say @maany?

**Comment by nimishbongale** [comment]
* [x]  Rule View
* [x]  DID View
* [x]  List My Rules
* [x]  Request New Rules
