### ISSUE TITLE
Authentication workflows in WebUI 2.0

### ISSUE THREAD

**Issue by maany** [rucio/webui#21]
Investigate mechanisms for authentication of users via the UI, that do not require direct database access, can utilize sessions from the server-side, and can rely on cookie management features provided by frontend frameworks like ReactJS.

----
Concrete Deliverables
- [x] Create a login page and corresponding React Components
- [ ] Create an architectural diagram for OIDC workflows.
- [ ] Implement OIDC authentication workflow and implement corresponding server-side endpoints
- [ ] Create an architectural diagram for x509 workflows.
- [ ] Implement x509 authentication workflow and implement corresponding server-side endpoints
- [ ] Create an architectural diagram for userpass workflows.
- [ ] Implement userpass authentication workflow and implement corresponding server-side endpoints

**Comment by nimishbongale** [comment]
Please assign this to me @maany, thanks!

**Comment by nimishbongale** [comment]
* [x]  Create a login page and corresponding React Components
* [x]  Create an architectural diagram for OIDC workflows.
* [x]  Implement OIDC authentication workflow and implement corresponding server-side endpoints
* [x]  Create an architectural diagram for x509 workflows.
* []  Implement x509 authentication workflow and implement corresponding server-side endpoints
* [x]  Create an architectural diagram for userpass workflows.
* [x]  Implement userpass authentication workflow and implement corresponding server-side endpoints
