### ISSUE TITLE
Page DID

### ISSUE THREAD

**Issue by ThePhisch** [rucio/webui#276]
Connect the endpoints:
- [x] didMeta: `DIDMetaViewModel`;
- [x] #317
- [x] #295
- [x] #319
- [x] #290
- [x] #323
- [x] #322

**Comment by maany** [comment]
didParentsComDOM -> https://rucio.github.io/documentation/html/rest_api_doc.html#tag/Data-Identifiers/paths/~1dids~1%7Bscope_name%7D~1parents/get 

didFileReplicasComDOM -> https://rucio.github.io/documentation/html/rest_api_doc.html#tag/Replicas/paths/~1replicas~1list/post
not sure about what state should be returned

didFileReplicaStateDViewModel: will need to group data in the usecase

didContentsComDOM: https://rucio.github.io/documentation/html/rest_api_doc.html#tag/Data-Identifiers/paths/~1dids~1%7Bscope%7D~1/get (with recursive flag)

didDatasetReplicasComDOM: https://github.com/rucio/rucio/blob/7f0d229ac0b3bc7dec12c6e158bea2b82d414a3b/lib/rucio/core/replica.py#L2737

**Comment by maany** [comment]
@ThePhisch  I am a bit lost in figuring out what view models you need. Could use some help!

To put it simply, there are 2 view models you request: `FileReplicaStateViewModel` and `FileReplicaStateDViewModel`

In `PageDIDFilereplicasD`
https://github.com/rucio/webui/blob/3932395f8b344fd6eef9c5ae3361e17033a0c6d1/src/component-library/Pages/DID/PageDIDFilereplicasD.tsx#L19
you use a ComDOM to stream `FileReplicaStateDViewModel` 

and then you print the `scope:name` in the table column.

https://github.com/rucio/webui/blob/3932395f8b344fd6eef9c5ae3361e17033a0c6d1/src/component-library/Pages/DID/PageDIDFilereplicasD.tsx#L27

So, looking at the entity `FileReplicasStateD`
https://github.com/rucio/webui/blob/3932395f8b344fd6eef9c5ae3361e17033a0c6d1/src/lib/infrastructure/data/view-model/page-did.d.ts#L14

it seems the entity contains the scope and name of a file in a dataset.

In the same file, you have a replica ComDOM that streams `FileReplicaStateViewModel`
https://github.com/rucio/webui/blob/3932395f8b344fd6eef9c5ae3361e17033a0c6d1/src/component-library/Pages/DID/PageDIDFilereplicasD.tsx#L63

This subpage/view renders the `rse:state`. However, how does this subpage know for which DID it is rendering the information for?

For example in the `PageDIDFilereplicasD`, when a user selects a file, the `PageDIDFilereplicas ` should render the replicas of the selected file. How is this information being passed?

I somehow feel we might need to re-define these 2 view models. `FileReplicaStateDViewModel` should contain a list of files and each file should contain a `FileReplicaState`. 
For cases when the DID type is File, the view model will just contain `FileReplicaState`

Let's discuss this in person if you prefer.

Minor request: Can we rename Filereplicas to FileReplicas

**Comment by ThePhisch** [comment]
working on it

**Comment by maany** [comment]
All nextjs endpoints are done @ThePhisch :)

**Comment by ThePhisch** [comment]
closed with #341
