### ISSUE TITLE
List Subscription

### ISSUE THREAD

**Issue by ThePhisch** [rucio/webui#278]
Connect:
- [x] #368
- [x] #363
- [x] #364
- [x] #370 
- [x] #374

**Comment by maany** [comment]
Hey @ThePhisch , the endpoint for this is available here:
https://github.com/rucio/webui/blob/master/src/pages/api/list-subscription.ts

**Comment by maany** [comment]
Rucio Endpoint: https://rucio.github.io/documentation/html/rest_api_doc.html#tag/Replicas/paths/~1subscriptions~1%7Baccount%7D~1%7Bname%7D~1Rules~1States/get
