### ISSUE TITLE
React Component Library Documentation

### ISSUE THREAD

**Issue by maany** [rucio/webui#3]
Motivation
----------
[Styleguides](https://react-styleguidist.js.org/) are great for documenting the react components, making it easier for different developers to collaborate and for stakeholders to visualize the UI.

Modification
------------
Install and configure `react-styleguides.js`

**Comment by nimishbongale** [comment]
@maany 

We have opted for storybook instead of styleguidist, here's a blog explaining the differences in both:

https://www.chromatic.com/blog/storybook-vs-styleguidist/

Let me know if this ticket can be assigned + closed, thanks!

**Comment by nimishbongale** [comment]
Closing this as our storybook hosted [here](https://rucio.cern.ch/webui) gives you all our components, and the documentation associated with them as well.
