### ISSUE TITLE
Page RSE

### ISSUE THREAD

**Issue by ThePhisch** [rucio/webui#302]
E2E Finish Page RSE
- [x] #337
- [x] #339
- [x] #344

**Comment by maany** [comment]
@ThePhisch p.s. Rucio does not stream the data required for `RSEProtocolViewModel` and `RSEAttributeViewModel`. Could you update the frontend to not use the ComDOM and render data from a single list of `RSEProtocolViewModel` or a single list of `RSEAttributeViewModel` ?

**Comment by maany** [comment]
@ThePhisch some changes will be required on the react side.
- `RSEProtocols` and `RSEAttributes` are not streamed, they will be returned as a list of each corresponding entity 
- `RSEProtocol` entity will not contain `created_at`/`updated_at` and the wan priorities will not contain `tpc` fields. I have made them optional, but you can remove them once the frontend has been adapted

**Comment by ThePhisch** [comment]
closed with #348
