### ISSUE TITLE
move incorrect viewmodels to entity

### ISSUE THREAD

**Issue by maany** [rucio/webui#320]
### Description

There are certain places in the code where the view models are used as entities. For example,
https://github.com/rucio/webui/blob/3932395f8b344fd6eef9c5ae3361e17033a0c6d1/src/lib/infrastructure/data/view-model/page-did.d.ts#L14-L33

All of the data structures in the file above are entities and not view models. They should therefore be ported to `lib.core.entity` module.

There could be other instances of this, @ThePhisch will know ;) 

For now, I will generate new API components using the entities declared in viewmodels, so that it is easier to refactor everything altogether

**Comment by maany** [comment]
@MytsV same as #297 , it will not be affected by us changing/upgrading frameworks

**Comment by MytsV** [comment]
Seems like this has already been done in this commit https://github.com/rucio/webui/commit/54eafde16f09f07ebad2462537e57dae5b3e0bdc
