### ISSUE TITLE
Use `useResponsiveHook` more frequently

### ISSUE THREAD

**Issue by ThePhisch** [rucio/webui#366]
* The hook is currently misspellt `useReponsiveHook`
* The hook combines logic for the creation of a listener for any window resizing and combines it with the Tailwind Thresholds
* It returns an object that contains booleans which correspond to *is it md (sized)* or *is it lg (sized)*

Use this hook more often, it cleans the codebase.

eg
```tsx
const responsive = useResponsiveHook()
//...
<StreamedTable
  //...
  tableStyling={{
    visibility: { tableid: responsive.md }
  }}
>
//...
```

**Comment by maany** [comment]
This will overload the browser when resizing. Use CSS ( Tailwind breakpoints) instead.
