### ISSUE TITLE
Add a configuration engine

### ISSUE THREAD

**Issue by maany** [rucio/webui#37]
Since the WebUI will be used by several rucio communities, its UI needs to be customizable based on environment variables and/or configuration files provided during its deployment.
At present, the  [`rucio.cfg`](https://github.com/rucio/rucio/blob/a5b3706fdf6085fb0d80ad697357972a6edc5d74/etc/rucio.cfg.template#L237-L249) and [environment variables](https://github.com/rucio/containers/tree/master/ui) are used to configure the old UI. 
In most Kubernetes-based deployments, the configuration is supplied as environment variables and then a rucio.cfg is generated at a later stage.

For the new UI, since it is independent of rucio server and rucio core, we would not require a section in `rucio.cfg`, and can just use environment variables directly to configure the app.

To begin with, the oidc config variables specified in [rucio.cfg](https://github.com/rucio/rucio/blob/a5b3706fdf6085fb0d80ad697357972a6edc5d74/etc/rucio.cfg.template#L237-L249) must be made available to the app via environment variables.

**Comment by nimishbongale** [comment]
@maany As per my research, there is a dotenv npm package that we could leverage for this use case, and all the variables we need. Then we can add a helper utility function say `env('key')` which returns the value, accessible with `process.env['key']`.

**Comment by maany** [comment]
Yup `dotenv` is well known and we should definitely leverage it. Please proceed with the helper utility around it :)
