### ISSUE TITLE
DID Page:  Redirects from List DID lead to /dids/<undefined>/<undefined>

### ISSUE THREAD

**Issue by maany** [rucio/webui#427]
### Description

On the integration cluster, we are noticing the when you select a DID from the List DIDs view, the redirect takes you to /dids/undefined/undedined. The expected behaviour is to take you to /dids/scope/name based on the selected DID.

This indicates a bug in the DID parsing login on the frontend. The reason we only see this in integration is because in the dev environment, did names are simple and might not contain any special characters.

### Steps to reproduce

1. Go to List DID page
2. Search for "mock:*"
3. Click on any DID in the table
4. Click Go to DID Page
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/2fab32f8-74a8-497c-a96e-f04f1aa64894">

<img width="1331" alt="image" src="https://github.com/user-attachments/assets/8795bd16-02c0-41c1-a119-2a4128004332">

### Rucio WebUI Version

35.0.0

**Comment by MytsV** [comment]
Another problem seen on these screenshots is information about a DID not loading on a side panel in the list view. It is related to incorrect request handling and will be fixed in a PR attached to this issue.

**Comment by MytsV** [comment]
> Another problem seen on these screenshots is information about a DID not loading on a side panel in the list view. It is related to incorrect request handling and will be fixed in a PR attached to this issue.

Seems like that was the issue after all, proofs will be in the attached PR
