### ISSUE TITLE
Create Rule : Connect to Create Rule feature and load Summary Page

### ISSUE THREAD

**Issue by maany** [rucio/webui#433]
### Description

Connect the Submit button in the Rule Overview tab to trigger the create rule feature.
Show the output of the create rule feature in the summary page.

### Additional Information

- [ ] The Rucio API needs to be changed.

**Comment by MytsV** [comment]
A Create DID sample endpoint should be created as well. The implementation is following:
![image](https://github.com/user-attachments/assets/9031dcac-f560-4c0d-bb17-cbeb84fa7fce)

**Comment by MytsV** [comment]
how the new scope is handled in current UI:
new_name = new_scope + '.' + did['name'] + '_der' + parseInt((Date.now() / 1000));
