### ISSUE TITLE
Dashboard: remove mocks and connect with real data

### ISSUE THREAD

**Issue by maany** [rucio/webui#436]
### Description

The dashboard currently renders mock data.
We need to create api endpoints and features to retrieve the required data.
This may require adding new endpoints to rucio

### Additional Information

- [X] The Rucio API needs to be changed.

**Comment by MytsV** [comment]
# Proposed request flow

Here's a draft of the request flow to the Rucio Server. The assumption currently is that the bar chart is supposed to be "locks per RSE".

## Locks per RSE
![image](https://github.com/user-attachments/assets/df3507cb-91e8-4083-bc0c-1f444c3e289d)
![image](https://github.com/user-attachments/assets/c6901fc0-fad5-47b7-972c-2e25ee531f91)

## RSE usage
![image](https://github.com/user-attachments/assets/42979ef2-70a0-4ea1-a18e-27435ccf9560)

# Notes

- There are two ways of handling data for the bar chart. We may either return a whole stream of locks (then the client counts each state of locks per RSE itself) or a ready view model:
```
[
  {
    "rse": "...",
    "ok_count":  5,
    "replicating_count": 10,
    "stuck_count": 0
  }
]
```
- There needs to be a list of RSEs to choose from
- I can't seem to find anything about the "may exceed quota" attribute
- In the old UI, RSE Usage and RSE Account Usage are separate views. As they get their data from different endpoints (as illustrated on the scheme above), shouldn't they be different dashboard widgets here as well to avoid confusion?

**Comment by MytsV** [comment]
There's an existing API page for only one of these features (list-account-rse-quotas). However, the usecase is calling two gateways, one of which isn't utilized in the UI and requires additional parameters. 

There's a list rules endpoint, but it's missing a way to specify an account.

The list-rule-replica-lock-states endpoint fulfills the requirements.

There's no gateway for fetching the general RSE usage.

## Summary

- A new usecase/controller and API page should be done for only listing RSE account usage
- The list-rules endpoint should be edited to allow account specification. All the needed structural elements should be added to connect it to an API page
- All the needed structural elements should be added to connect list-rule-replica-lock-states endpoint to an API page
- A gateway for the general RSE usage should be added along with a usecase/controller

**Comment by MytsV** [comment]
# Proposed UI changes

The dashboard should be made more convenient with the usage of tabs or some delimiters for the widgets. Problems with accessibility should be addressed. Human readable amount of disk space should be displayed.

I feel like building it from scratch may be quicker and more reliable than working on top of the current implementation.
