### ISSUE TITLE
Change the background of the RSE protocols table header 

### ISSUE THREAD

**Issue by MytsV** [rucio/webui#440]
### Description

The backgrounds of last few columns headers seem too light and clash with the white text.
![image](https://github.com/user-attachments/assets/27cca281-3df2-43bd-b33f-2a3f563f20f9)

### Motivation

Improve readability and accessibility of the page.

### Change

Make either the background or text color darker.

### Additional Information

- [ ] The Rucio API needs to be changed.

**Comment by MytsV** [comment]
May be replaced by completing #431

**Comment by maany** [comment]
Oh no!! If this is just a tailwind class name gone wrong situation, could you please add the right class here @MytsV . Thanks
