### ISSUE TITLE
WebUI should escape slash characters when sent to server

### ISSUE THREAD

**Issue by ericvaandering** [rucio/webui#485]
### Description

Several communities (CMS included) use slashes in the DIDs. When not escaped, these confuse REST APIs.

### Steps to reproduce

Mayank and I reproduced this

### Rucio WebUI Version

35.x

**Comment by MytsV** [comment]
Hello @ericvaandering!

Thank you for reporting this bug!

A pull request with an apparent fix has been attached and will be merged into master soon. I hope this resolves the issue!

Best regards,
Victoria
