### ISSUE TITLE
PROJECT_URL does not update the link when clicking the experiment icon

### ISSUE THREAD

**Issue by d-ylee** [rucio/webui#495]
### Description

After setting PROJECT_URL environment, I believe the proper behavior would be to have the experiment icon in the navigation bar link to the provided PROJECT_URL. Currently, the icon will link to https://atlas.cern.

### Steps to reproduce

1. Set PROJECT_URL or RUCIO_WEBUI_PROJECT_URL
2. Deploy WebUI in OKD/k8s
3. Login and click on experiment icon/logo

### Rucio WebUI Version

35.3.0

### Additional Information

- Deployed on OKD4
- Chrome 129.0.6668.101

**Comment by MytsV** [comment]
Hello @d-ylee!

Thank you for bringing this to our attention!

I've attached a pull request which resolves this issue. It will be merged into master in a while.

Best regards,
Victoria
