### ISSUE TITLE
header-lint for ts or js files

### ISSUE THREAD

**Issue by maany** [rucio/webui#5]
Motivation
----------

The `rucio\rucio` repository uses `header-lint` script to ensure consistent headers across all source files. We could use the same script or something similar here as well.

Modification
---------
1. Add header-lint script from `rucio/rucio`. 
2. update the pre-commit hooks to include header-linting
3. add the header-lint step in the autotest workflow

**Comment by joeldierkes** [comment]
The header lint script gives me a big headache. While I like the idea of explicitly listing all contributors to a source file, the header lint generates **a lot** of noise in the commits. They make the actual changes harder to read and pollute the history. The logic is, at the same time, fairly complex and not easy to implement. We still have multiple problems with the original header lint script.

There are sophisticated git tools to list the contributors of a file, they should be used instead.

We could create a script to add a generic Copyright information to the files, however I would **strongly** avoid to insert the contributors.

**Comment by maany** [comment]
Hey @joeldierkes, seeing the fate of header-lint in the main rucio repo, I agree with you. Would you have time to add a script to add copyright notice to the files changed in a PR. :)

**Comment by maany** [comment]
bump @joeldierkes
