### ISSUE TITLE
Remove .env file from the repository

### ISSUE THREAD

**Issue by maany** [rucio/webui#64]
### Description

There is an empty .env file in the root of the webui repo. It can be removed and should be explicitly mentioned in the .gitignore, if it is not present there already

**Comment by nimishbongale** [comment]
@maany As per the README, it serves to define environment variables (mentioned within .env.template). An empty .env file would imply no environment variables.

We could do away with it, but imo having it would be better.

**Comment by maany** [comment]
It is a dynamic configuration which is not constant across deployments, so the .env file is not really adding any value to the source code repository. Putting the empty .env in the source code does not guarantee that people will go through the required list of env variables when setting up the project for deployments. So, IMO, we can get rid of it ;)

**Comment by nimishbongale** [comment]
Alright, will do away with it.

I can also see the `package-lock.json` committed. I don't think it's a good practice to commit the same?
