### ISSUE TITLE
Create a models.ts to mimic Rucio types

### ISSUE THREAD

**Issue by maany** [rucio/webui#81]
### Description

The data fetched from the server should be parsed into TypeScript classes.

### Change

Create a new models.ts file. Add models for `Account`, `Rule` types.

### Additional Information

- [ ] The Rucio API needs to be changed.

**Comment by nimishbongale** [comment]
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

**Comment by nimishbongale** [comment]
Closed as a part of #90
