### ISSUE TITLE
Custom Exceptions

### ISSUE THREAD

**Issue by maany** [rucio/webui#82]
### Description

We should provide cusotm exceptions to clearly indicate errors with fetching data from Rucio REST APIs or Authentication servers

### Change

 - Create a new exceptions.ts file
 - Define exceptions related to login methods. 
 - Use the exceptions in the codebase 

### Additional Information

- [ ] The Rucio API needs to be changed.

**Comment by nimishbongale** [comment]
https://github.com/adriengibrat/ts-custom-error

**Comment by maany** [comment]
Let's give it a shot!

**Comment by nimishbongale** [comment]
Closed as a part of #90
