### ISSUE TITLE
Prototype a Rucio Client

### ISSUE THREAD

**Issue by maany** [rucio/webui#83]
### Description

The flask blueprints for the [rucio server](https://github.com/rucio/rucio/tree/master/lib/rucio/web/rest/flaskapi/v1) are organized into logical endpoint groups ( did, account, rule, subscription etc.. etc..).
We can mimic the structure and create a JS Client for each of these endpoints.

### Change

- Add endpoints for rules, auth
- Make sure a valid Rucio Auth Token is automatically attached to the requests
- Create custom exceptions where necessary

### Additional Information

- [ ] The Rucio API needs to be changed.

**Comment by nimishbongale** [comment]
Dependent on #82
