### ISSUE TITLE
PKCE with OIDC/OAuth2

### ISSUE THREAD

**Issue by maany** [rucio/webui#86]
### Description

The environment variables passed to the application are bundled in the build produced by webpack. Therefore, any secret values in the environment variables are actually accessible by the end-user's browsers.
![image](https://user-images.githubusercontent.com/5906242/189613767-a2647ae1-bc57-4896-953b-32e56d680d50.png)

We cannot store the `Client Secret` for the webui as an environment variable and this is a known [vulnerability for single-page apps](https://www.oauth.com/oauth2-servers/single-page-apps/) like the new webui.
The correct way to handle single page apps was to use the `Implicit Grant Type`, however, this has been deprecated in favor of the `PKCE with Authorization Code` flow. [RFC7636](https://www.rfc-editor.org/rfc/rfc7636#page-5) describes this workflow.

A good article I found on this new workflow is [here](https://dropbox.tech/developers/pkce--what-and-why-#:~:text=%E2%80%9CPKCE%20(RFC%207636)%20is,to%20access%20their%20Dropbox%20data.)

The OIDC/OAuth2 workflow must be adapter to use `code_verifier` and `code_challenge` in its token and authorization requests respectively instead of the `client_secret`. If an oauth provider does not support PKCE with Authorization Code workflow, an error should be raised on the client side.

### Rucio WebUI Version

master

**Comment by nimishbongale** [comment]
- https://www.npmjs.com/package/react-oauth2-code-pkce
- https://github.com/soofstad/react-oauth2-pkce#all-configuration-parameters
